### ISSUE TITLE
Add badges for readme using npm-badger

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/nlen-num#11]
1. Install npm badger `npm install npm-badger -g`
2. Clone this repository `git clone https://github.com/arshadkazmi42/nlen-num`
3. Go to root directory `cd nlen-num`
4. Run npm badger `npm-badger`
5. Commit `README.md` file
6. Create Pull Request

**Comment by tuhinmallick** [comment]
Is this issue still available then I would like to give it a try.

**Comment by arshadkazmi42** [comment]
Yes, it is available.

**Comment by MTA777** [comment]
Is this issue is still available then I would like to give it a try.

**Comment by arshadkazmi42** [comment]
@tuhinmallick are you still working on this? Otherwise I can assign it to @MTA777

**Comment by arshadkazmi42** [comment]
This is fixed in #15
